### ISSUE TITLE
Code block not closed in Afrikaans locale

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora-project-site#104]
On https://diasporafoundation.org/formatting, the code block is not properly closed at the end of a string, and so extends to the end of the page.

The affected string is `pages.formatting.code_ex3`, and the problem is that the code block is improperly closed by `</ code>` (with a space in it).

I've tried to correct this at WebTranslateIt – [string here](https://webtranslateit.com/en/projects/7017-Website/locales/en..af/strings/4545597) – but I don't have permissions for Afrikaans, so I can't.

If someone could fix it, that would be great!

**Comment by denschub** [comment]
I edited it and will deploy soon. Also, I invited you as a manager into the project on webtranslateit. As it seems, you were not even part of the website-project before. :)
