### ISSUE TITLE
http2 or quic is needed ?!

### ISSUE THREAD

**Issue by zez3** [diaspora/diaspora-project-site#109]
Hi there,
I just joined and noticed that it is quite slow and that there is no HTTP2 active on it.
Can you at least enable HTTP2 ?
Thanks.

**Comment by SuperTux88** [comment]
I don't think that http2 makes a big difference on the project site, because it doesn't have that many requests, and I think it's already quite fast. But sure, sooner or later it hopefully has http2 too, but it has no priority.

**Comment by denschub** [comment]
Server supports http2 for like 4 years or so.
