### ISSUE TITLE
diasporafoundation.org language should follow browsers acceptLanguage header

### ISSUE THREAD

**Issue by ThorstenClaus** [diaspora/diaspora-project-site#130]
The main project site 'https://diasporafoundation.org' has several localizations. Todays browser are sending a AcceptLanguage Header that seems not to be evaluated. 

A user should see by default the page (every diaspora page) in the suggested language sent by the browser with a fallback to English.

**Comment by denschub** [comment]
Unless you have a `locale` cookie, which you will get for manually changing the language, the project site does exactly that.

```
# curl -s -H "Accept-Language: en" https://diasporafoundation.org/ | grep "<title"
  <title>The diaspora* Project</title>

# curl -s -H "Accept-Language: de" https://diasporafoundation.org/ | grep "<title"
  <title>Das Projekt diaspora*</title>
```

**Comment by ThorstenClaus** [comment]
👍🏻 Nice- thank you. That works.
