### ISSUE TITLE
Update tutorials

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora-project-site#73]
With the release of diaspora\* v0.5.0.0, some information in the tutorials are not valid anymore. We need to read the whole tuto to check what's fine and what's wrong.

**Comment by goobertron** [comment]
Ah, nice work. I just came here to open the same issue. Let's use this as a catch-all issue and ask people to post the updates they notice are necessary.

**Comment by goobertron** [comment]
I have just made a few interface updates in #83, to take account of changes in v0.5 and v0.6. @Flaburgan do you want to have a look through and tell me of anything else you notice which is out of date (once this PR has been made live)? There are some more screenshots which do not reflect the current UI, but if you see any text which is now redundant or explanations of new features which are missing, please let me know.

**Comment by Flaburgan** [comment]
@denschub can you please ping me here once you updated the website?

**Comment by goobertron** [comment]
@Flaburgan you can pull the code and look at it locally, if you have time. I'm hoping to get the tutorials updated in time for the release of 0.6, and it would be nice to be able to get all the updates (#83 included) out in one go (along with translations of any new text).

**Comment by denschub** [comment]
@Flaburgan Pushed to production, the deployment should be done in some minutes.

**Comment by Flaburgan** [comment]
@goobertron didn't have time to do the review yet, but the new publisher has been merged, so some new screenshots are needed I guess ;)

**Comment by goobertron** [comment]
Dammit, I updated the publisher screenshot last week!

OK, will get on to it, and an explanation of the new features in the publisher. Thanks for letting me know.

**Comment by Flaburgan** [comment]
With https://github.com/diaspora/diaspora-project-site/pull/84 being merged, I close this issue. We can open new more specific ones if we find something to update in the future.
