### ISSUE TITLE
Error on page https://diasporafoundation.org

### ISSUE THREAD

**Issue by Petrouchka** [diaspora/diaspora-project-site#78]
On the page https://diasporafoundation.org (in french), the link toward pods list is missing :
"Une liste des pods de la communauté est disponible ici %{poduptime}."

**Comment by goobertron** [comment]
I've just checked this out, and the French translation is different from the English text. I guess the English has been updated at some point, but not the French.

The sentence 'Choose from among our community pods, perhaps one based in your locality.' is replaced by 'Une liste des pods de la communauté est disponible ici %{poduptime}.' ('A list of community pods is available here %{poduptime}.')

The Pod Uptime link appears in the next block of text, so is not needed here.

This fix needs to be made at https://webtranslateit.com/en/projects/7017-Website/locales/en..fr/strings?current_id=4512446 under `pages.index.sign_up_ex`. I don't want to do this myself as my French isn't good enough. @Flaburgan or @AugierLe42e would you be happy to step in and fix this?

**Comment by Flaburgan** [comment]
I can fix that, though the full english text is:
>Find a pod that suits you. You might prefer a smaller pod, or one based near where you live, or one based in a country that you know has good data security policies. The choice is yours! Choose from among our community pods, perhaps one based in your locality.

So the problematic sentence looks redundant in english to me. Should we remove it? @goobertron do you want to formulate it differently?

**Comment by goobertron** [comment]
Actually, you're right - it is redundant.

In fact, on reflection I think there should be mention in this paragraph of the possibility of hosting a pod yourself. How about:

> Find a pod that suits you. You might prefer a smaller pod, or one based near where you live, or one based in a country that you know has good data security policies. **Or, if you're comfortable with basic sysadmin, you can host your own pod.** The choice is yours!

I'd suggest the new sentence links either to https://diasporafoundation.org/about#host or https://wiki.diasporafoundation.org/Installation_guides

Would value input on the wording of the new sentence - do we want to say something along the lines of 'if you're competent enough' (like the example above), or something like 'if you're feeling adventurous/up for a challenge', or something different? What's the best way to encourage people about the option of setting up a pod?

**Comment by Petrouchka** [comment]
diaspora* website is down today (error 500).

**Comment by svbergerem** [comment]
@Petrouchka Works for me. Is the website still broken for you? If so, which is the preferred language you set in your browser?

**Comment by Petrouchka** [comment]
Still error 500 :
![capture du 2017-01-29 13-22-11](https://cloud.githubusercontent.com/assets/3955499/22403932/ff853fec-e625-11e6-8e55-f4b72a9fce96.png)

**Comment by svbergerem** [comment]
It's broken in French.

**Comment by svbergerem** [comment]
@Petrouchka See #97.
