### ISSUE TITLE
interface instructions for stream and public activity

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora-project-site#82]
See https://github.com/diaspora/diaspora/issues/6941

**Comment by denschub** [comment]
Please elaborate your idea.

**Comment by githubgnulinux** [comment]
See https://diasp.eu/posts/4489425#2d555f203d1a013403245404a6b20780

**Comment by denschub** [comment]
No. I will not click your links to random posts. We've told you before that we use GitHub and Loomio, not diaspora. If you want to submit something, then submit it here. Please write GitHub issues that are actually useful and contain a clear description. We've told you this before and it starts getting really, really exhausting.

**Comment by goobertron** [comment]
It's difficult to tell what the actual request is here, even after following several links. However, I *think* the request is simply to add a note about the new Public activity stream to the tutorials.

This has been done in #83, along with various other updates relating to the UI.

**Comment by goobertron** [comment]
Fixed via #83.
