### ISSUE TITLE
tags, federation, aspects

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora-project-site#85]
https://diasp.eu/posts/4513054

**Comment by svbergerem** [comment]
This issue needs some more information. Just posting a link to a diaspora\* post is not nice. You are expecting devs to go over there to get the info they need but this issue tracker is more efficient when we have all information in one place. Please add your information to the description of this issue.

**Comment by githubgnulinux** [comment]
Arbritary discrimination is also not nice.

As shown previously (e.g. https://github.com/diaspora/diaspora/issues/6938), programmers take self-declared decisions to determine what is a bug, when discussions should be closed and discriminates who should participate in discussions.

This discriminatory powers don't (yet?) exist in diaspora, therefore all comments/information will be published there and never again in github.

**Comment by AugierLe42e** [comment]
Dude, why can't you just add a few lines of explanations instead of just always complaining!?
To answer your question: whether tags are federated or not is irrelevant. There are two situations here:

1. the author has posted in public or in an aspect you're in,
2. the author has posted in an aspect you're not.

In the first case, the post is federated with your pod and you should be able to see it searching by tags. In the second case, you should not be able to see it. There's really nothing to explain here...

**Comment by border0464111** [comment]
http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by denschub** [comment]
> therefore all comments/information will be published there and never again in github.

Thank you for making clear you are not interested to contribute in a sane manner.

I never really thought I have to use this feature of GitHub organizations, but @githubgnulinux is now blocked from this organization. This means that they'll be no longer able to create issues or interact with existing issues in any way. 31 invalid issues and countless counterproductive comments are more than enough. We've tried to resolve issues we've had with them many times before, but I feel like they are simply not willing to contribute in a manner that's actually useful. :(

In addition, closing this issue as invalid. I really do not like guessing games in project issues and I doubt we will get any clearer information on this. Opening a new issue with concrete information is just a few clicks anyway.

**Comment by border0464111** [comment]
sad to reach this point but it's justified IMO 

+1
