### ISSUE TITLE
Privacy and data ownership selling points are somewhat inaccurate

### ISSUE THREAD

**Issue by Hypolite** [diaspora/diaspora-project-site#86]
Hi all,

I recently started [a thread on Loomio](https://www.loomio.org/d/RktYIM0W/push-feature-reinquinshing-control-over-data) about the marketing message on the Diaspora* homepage regarding Privacy and data ownership. Specifically, I think that the content (especially private conversations) replication between pods through push updates is going against the Privacy promise that is currently stated as follow:

> ### Privacy
> In diaspora* you own your data. You do not sign over any rights to a corporation or other interest who could use it. With diaspora*, your friends, your habits, and your content is your business ... not ours! In addition, you choose who sees what you share, using Aspects.

Let's go bit by bit:

> you own your data

This is true as long as you are hosting your own pod and you only communicate with users signed up on your pod. As soon as you start interacting with users from other pods, your content (public, limited or private) get sent to other databases that you don't own. Sure, other pods are expected to remove the duplicated content when you delete it on your pod, but you can't make them if they don't want, and even if they comply with deletion requests remote podmins have access to this content while it's up on your pod as well.

> You do not sign over any rights to a corporation or other interest who could use it.

This is true, nothing is signed, but your data is out nonetheless. Nothing prevents your podmin to use its pod's data and sell it to the highest bidder. And right now there isn't an easy way to move from a untrustworthy pod to another one. There's a limited amount of personal informations that are shared between pods, which prevent remote podmins to collect too much information, but this possibility exists as well.

> With diaspora*, your friends, your habits, and your content is your business ... not ours!

This is almost true as well. The Diaspora* dev team doesn't have direct access to a specific individual user's data, unless they happen to be podmin of their pod. I'm not sure how much Diaspora* devs are also podmins, but again, the wording leaves no doubt when they could be one.

> In addition, you choose who sees what you share, using Aspects.

This is a regular feature description and poses no problem to me whatsoever.

I think it's worth considering a rewriting of this section, and maybe emphasizing that everything you post on Internet may become public, Diaspora* or not. Other encryption services are providing real privacy services that Diaspora* simply can't match by design, and I feel like Diaspora*'s communication shouldn't present Privacy as a cornerstone for switching to it, at least not under this shape.

**Comment by goobertron** [comment]
Thanks for opening this. I agree that this paragraph can be improved. If you can suggest amendments/improvements, that would be a real help.

**Comment by Hypolite** [comment]
Let's take a stab at it. I'm hoping someone with better english writing skills can improve upon it.

> ## Privacy
> In Diaspora* you don't need to trust every single employee of a commercial company with your data. You mainly need to trust the podmin of the server you are registering with, and the podmins of the users you are sharing with, either through aspects or private message. No other podmin in the Diaspora* network can have physical access to your data, it simply is not there. This also means that no Diaspora*-wide data mining is available to any single podmin by design. And if you host your own pod, it's one less person to have to trust!

**Comment by goobertron** [comment]
Thanks for your suggestion, @Hypolite. That's more accurate, but looks to me as though it might be a bit too complicated for general users who don't already know how diaspora works. I'll take your suggestions on board, and think about it more.

**Comment by Hypolite** [comment]
Yeah, that's what I feared. I still think that accuracy is better than accessibility, but I'm already versed in the technical aspects, which makes me a poor judge of accessibility. I just don't want to mislead people, and that they would suddenly realize their data is out there somewhere when they thought it would stay with them.

Thanks for the comment!

**Comment by goobertron** [comment]
I agree that it's important not to mislead, but for that page we need it to be simple and clear as well as accurate. I've seen so many confused #newhere posts down the years from people who have signed up but don't understand what a pod is or even know that Diaspora is decentralised (as I didn't when I signed up in 2010), or in many cases even understand that a social network can be decentralised. They simply followed an invite link from a friend or clicked a link to a particular pod in an article about Diaspora.

Another point is length - there's only so much space on that page for the design to work visually, and some translations (e.g. French) tend to be a lot longer than English. We need to keep it short and snappy.

I thought last night that it might be possible to add something about this to https://diasporafoundation.org/about#privacy (the section which the 'Find out more' button links to, where there is more space and more detail. On first look today I can't see how that might be done, but it might be possible.

I'll think about it more, and if you or anyone else have more suggestions, please do make them!

**Comment by Hypolite** [comment]
I will, thanks!

**Comment by goobertron** [comment]
How about this for the first section under https://diasporafoundation.org/about#privacy ?

> ### Own your own data
> Many networks make money by analysing your interactions and using this to advertise things to you. diaspora* doesn’t use your data for any purpose other than allowing you to connect and share with others. **Only the admins of pods you interact with can access your data, and you can choose which pods you interact with.**

(New part in bold.)

**Comment by Hypolite** [comment]
That's better, however how do you choose which pod you interact with?

**Comment by goobertron** [comment]
By choosing who to share with.

**Comment by goobertron** [comment]
Have made a PR with that change, #88.

**Comment by pravi** [comment]
On Monday 19 September 2016 06:34 PM, goob wrote:
> How about this for the first section under
> https://diasporafoundation.org/about#privacy ?
> 
> 
>           Own your own data
> 
>     Many networks make money by analysing your interactions and using
>     this to advertise things to you. diaspora* doesn’t use your data for
>     any purpose other than allowing you to connect and share with
>     others. *Only the admins of pods you interact with can access your
>     data, and you can choose which pods you interact with.*
> 
> (New part in bold.)

I think we can mention end to encryption using XMPP for complete
privacy, even podmins can't get that info.

**Comment by goobertron** [comment]
But only the transport is encrypted - data on pods is not encrypted, so a podmin can access the data on their pod. See https://www.loomio.org/d/KQfdUlox/comment/37684

**Comment by pravi** [comment]
On Monday 19 September 2016 10:31 PM, goob wrote:
> But only the transport is encrypted - data on pods is not encrypted, so
> a podmin can access the data on their pod. See
> https://www.loomio.org/d/KQfdUlox/comment/37684

If they use an XMPP client that supports end to end encryption like
conversations or gajim with their diaspora accounts, they can use OMEMO
or PGP to encrypt data stored on the pod too. Yes, this is only
available in chat using a native app, but it is an important point to be
mentioned/highlighted I think.

If people don't want to trust even the podmins, they can use this option.

**Comment by goobertron** [comment]
OK, but the project website is not to teach people how to be secure online but to explain very simply how Diaspora works, and its benefits. What you describe may be a useful tip, but it's not part of the core code or the core Diaspora experience, so doesn't belong on the project site; and, in any case, anyone who needs to read the project site to understand how to use Diaspora is unlikely to be capable of using XMPP in this way. 

There might be a different means to spread the word about it - perhaps we could start sharing tips like this within Diaspora itself?

**Comment by pravi** [comment]
On 2016, സെപ്റ്റംബർ 19 10:54:04 PM IST, goob <notifications@github.com> wrote:
>OK, but the project website is not to teach people how to be secure
>online but to explain very simply how Diaspora works, and its benefits.
>What you describe may be a useful tip, but it's not part of the core
>code or the core Diaspora experience, so doesn't belong on the project
>site; and, in any case, anyone who needs to read the project site to
>understand how to use Diaspora is unlikely to be capable of using XMPP
>in this way. 

Chat is a recently added feature. But I don't agree it is not a core feature. XMPP real time chat is very much an important part of diaspora experience.

Well, the core idea behind diaspora is privacy and data ownership, so it is important we highlight this option.

>There might be a different means to spread the word about it - perhaps
>we could start sharing tips like this within Diaspora itself?

That we can do, but I consider it part of the core idea of diaspora itself.

**Comment by goobertron** [comment]
Chat is only available on certain pods, so is not discussed on the project website.

**Comment by goobertron** [comment]
Now fixed by #88, so I believe this issue can be closed.

**Comment by Hypolite** [comment]
Thanks @goobertron !
